### ISSUE TITLE
Server Restart when create a island

### ISSUE THREAD

**Issue by Zsomi** [aglerr/SSB2-AdvancedSlimeWorldManager#4]
When players create the island it barely takes 1 minute but the server restarts.

Error code:

https://pastebin.com/fsvJ3skJ

**Comment by mdaffa48** [comment]
This issue has been answered by Ome_R (SuperiorSkyblock2 author). From the comment he made, he says that the cause of server restarting/crash is because of Paper's anti-xray feature.

> However, when teleporting to your islands after a restart, there seems to be errors with Paper's anti-xray. If you get errors and your server crash, just disable the anti-xray of Paper (which is pointless anyways on a skyblock server)

References:
https://github.com/aglerr/SSB2-AdvancedSlimeWorldManager/issues/2#issuecomment-1007977588
